/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Connector2to3 (props) {
  const { nodes, materials } = useGLTF("./models/connector2-3.glb");
  return (
    <group {...props} dispose={null}>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Cube021.geometry}
      material={materials.metal}
      position={[-115.968, 2.835, -16.98]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Cube175.geometry}
      material={nodes.Cube175.material}
      position={[-116.605, 9.371, -12.236]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Cube176.geometry}
      material={nodes.Cube176.material}
      position={[-116.605, 9.371, -23.643]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Cube177.geometry}
      material={nodes.Cube177.material}
      position={[-116.605, 9.371, -34.971]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Cube178.geometry}
      material={materials["white light"]}
      position={[-71.754, 2.513, -43.503]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Cube179.geometry}
      material={materials["white light"]}
      position={[-71.754, 14.178, -43.503]}
    />
    <group position={[-102.269, -0.181, 1.197]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube059.geometry}
        material={materials.blanc}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube059_1.geometry}
        material={materials["white light"]}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Cube005.geometry}
      material={materials.metal}
      position={[-71.196, 2.427, -41.137]}
    />
    <group position={[-88.524, -0.153, -27.044]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={materials.blanc}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027_1.geometry}
        material={materials.orange}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Plane069.geometry}
      material={materials.metal}
      position={[-87.129, 10.456, -31.843]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Plane070.geometry}
      material={materials.metal}
      position={[-87.129, 9.119, -31.843]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Plane071.geometry}
      material={materials.metal}
      position={[-87.129, 7.744, -31.843]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Plane072.geometry}
      material={materials.metal}
      position={[-87.129, 6.672, -31.843]}
    />
    <group
      position={[-108.332, 1.558, -39.351]}
      rotation={[-3.075, 0.01, 1.573]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder046.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder046_1.geometry}
        material={materials["metal orange"]}
      />
    </group>
    <group
      position={[-100.517, 1.558, -39.351]}
      rotation={[-3.075, 0.01, 1.573]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder047.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder047_1.geometry}
        material={materials["metal orange"]}
      />
    </group>
    <group
      position={[-93.039, 1.558, -39.351]}
      rotation={[-3.075, 0.01, 1.573]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder048.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder048_1.geometry}
        material={materials["metal orange"]}
      />
    </group>
    <group
      position={[-85.339, 1.558, -39.351]}
      rotation={[-3.075, 0.01, 1.573]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder049.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder049_1.geometry}
        material={materials["metal orange"]}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Cube171.geometry}
      material={materials.metal}
      position={[-144.498, 1.153, -22.11]}
    />
    <group
      position={[-112.681, -5.766, -37.003]}
      rotation={[-1.179, -1.499, -2.746]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder063_1.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder063_2.geometry}
        material={materials["metal orange"]}
      />
    </group>
    <group
      position={[-124.427, -15.243, -19.144]}
      rotation={[-0.067, -0.048, -1.571]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder065_1.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder065_2.geometry}
        material={materials["metal orange"]}
      />
    </group>
    <group
      position={[-124.427, -5.477, -19.144]}
      rotation={[-0.067, -0.048, -1.571]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder066_1.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder066_2.geometry}
        material={materials["metal orange"]}
      />
    </group>
    <group
      position={[-112.892, -14.754, -37.003]}
      rotation={[-1.179, -1.499, -2.746]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder068.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder068_1.geometry}
        material={materials["metal orange"]}
      />
    </group>
  </group>
  );
}

useGLTF.preload("/connector2-3.glb");

